/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class AddressDTO
    {
        [DataMember()]
        public Int32 AddressID { get; set; }

        [DataMember()]
        public String Title { get; set; }

        [DataMember()]
        public String Line1 { get; set; }

        [DataMember()]
        public String Line2 { get; set; }

        [DataMember()]
        public String Line3 { get; set; }

        [DataMember()]
        public String City { get; set; }

        [DataMember()]
        public String State { get; set; }

        [DataMember()]
        public String ZipCode { get; set; }

        [DataMember()]
        public Nullable<Int32> CountryID { get; set; }

        [DataMember()]
        public Nullable<Int32> AddressTypeID { get; set; }

        [DataMember()]
        public CountryDTO Country { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        [DataMember()]
        public List<BusinessAddressDTO> BusinessAddresses { get; set; }

        [DataMember()]
        public List<UserAddressDTO> UserAddresses { get; set; }

        public AddressDTO()
        {
        }

        public AddressDTO(Int32 addressID, String title, String line1, String line2, String line3, String city, String state, String zipCode, Nullable<Int32> countryID, Nullable<Int32> addressTypeID, CountryDTO country, TypeCodeDTO typeCode, List<BusinessAddressDTO> businessAddresses, List<UserAddressDTO> userAddresses)
        {
			this.AddressID = addressID;
			this.Title = title;
			this.Line1 = line1;
			this.Line2 = line2;
			this.Line3 = line3;
			this.City = city;
			this.State = state;
			this.ZipCode = zipCode;
			this.CountryID = countryID;
			this.AddressTypeID = addressTypeID;
			this.Country = country;
			this.TypeCode = typeCode;
			this.BusinessAddresses = businessAddresses;
			this.UserAddresses = userAddresses;
        }
    }
}
