/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:11
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class BusinessDTO
    {
        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Abbreviation { get; set; }

        [DataMember()]
        public Nullable<DateTime> StartDate { get; set; }

        [DataMember()]
        public Int32 BusinessTypeID { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        [DataMember()]
        public Nullable<Int32> insuser { get; set; }

        [DataMember()]
        public Nullable<DateTime> insdt { get; set; }

        [DataMember()]
        public Nullable<Int32> upduser { get; set; }

        [DataMember()]
        public Nullable<DateTime> upddt { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public UserDTO User1 { get; set; }

        [DataMember()]
        public List<BusinessAddressDTO> BusinessAddresses { get; set; }

        [DataMember()]
        public List<BusinessEmailDTO> BusinessEmails { get; set; }

        [DataMember()]
        public List<BusinessPhoneDTO> BusinessPhones { get; set; }

        [DataMember()]
        public List<BusinessUserMapDTO> BusinessUserMaps { get; set; }

        [DataMember()]
        public List<JobDTO> Jobs { get; set; }

        public BusinessDTO()
        {
        }

        public BusinessDTO(Int32 businessID, String name, String abbreviation, Nullable<DateTime> startDate, Int32 businessTypeID, Boolean isActive, Boolean isDeleted, Nullable<Int32> insuser, Nullable<DateTime> insdt, Nullable<Int32> upduser, Nullable<DateTime> upddt, TypeCodeDTO typeCode, UserDTO user, UserDTO user1, List<BusinessAddressDTO> businessAddresses, List<BusinessEmailDTO> businessEmails, List<BusinessPhoneDTO> businessPhones, List<BusinessUserMapDTO> businessUserMaps, List<JobDTO> jobs)
        {
			this.BusinessID = businessID;
			this.Name = name;
			this.Abbreviation = abbreviation;
			this.StartDate = startDate;
			this.BusinessTypeID = businessTypeID;
			this.IsActive = isActive;
			this.IsDeleted = isDeleted;
			this.insuser = insuser;
			this.insdt = insdt;
			this.upduser = upduser;
			this.upddt = upddt;
			this.TypeCode = typeCode;
			this.User = user;
			this.User1 = user1;
			this.BusinessAddresses = businessAddresses;
			this.BusinessEmails = businessEmails;
			this.BusinessPhones = businessPhones;
			this.BusinessUserMaps = businessUserMaps;
			this.Jobs = jobs;
        }
    }
}
