/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class BusinessUserMapDTO
    {
        [DataMember()]
        public Int32 BusinessUserMapID { get; set; }

        [DataMember()]
        public Int32 BusinessID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public Boolean IsOwner { get; set; }

        [DataMember()]
        public Nullable<Int32> BusinessUserTypeID { get; set; }

        [DataMember()]
        public BusinessDTO Business { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        public BusinessUserMapDTO()
        {
        }

        public BusinessUserMapDTO(Int32 businessUserMapID, Int32 businessID, Int32 userID, Boolean isOwner, Nullable<Int32> businessUserTypeID, BusinessDTO business, TypeCodeDTO typeCode, UserDTO user)
        {
			this.BusinessUserMapID = businessUserMapID;
			this.BusinessID = businessID;
			this.UserID = userID;
			this.IsOwner = isOwner;
			this.BusinessUserTypeID = businessUserTypeID;
			this.Business = business;
			this.TypeCode = typeCode;
			this.User = user;
        }
    }
}
