/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class EmailDTO
    {
        [DataMember()]
        public Int32 EmailID { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public Nullable<Int32> EmailTypeID { get; set; }

        [DataMember()]
        public List<BusinessEmailDTO> BusinessEmails { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        [DataMember()]
        public List<UserEmailDTO> UserEmails { get; set; }

        public EmailDTO()
        {
        }

        public EmailDTO(Int32 emailID, String address, Nullable<Int32> emailTypeID, List<BusinessEmailDTO> businessEmails, TypeCodeDTO typeCode, List<UserEmailDTO> userEmails)
        {
			this.EmailID = emailID;
			this.Address = address;
			this.EmailTypeID = emailTypeID;
			this.BusinessEmails = businessEmails;
			this.TypeCode = typeCode;
			this.UserEmails = userEmails;
        }
    }
}
