/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class JobApplicationStateDTO
    {
        [DataMember()]
        public Int32 JobApplicationStateID { get; set; }

        [DataMember()]
        public Int32 JobApplicationID { get; set; }

        [DataMember()]
        public Int32 JobApplicationStatusID { get; set; }

        [DataMember()]
        public DateTime insdt { get; set; }

        [DataMember()]
        public Int32 insuser { get; set; }

        [DataMember()]
        public JobApplicationDTO JobApplication { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        public JobApplicationStateDTO()
        {
        }

        public JobApplicationStateDTO(Int32 jobApplicationStateID, Int32 jobApplicationID, Int32 jobApplicationStatusID, DateTime insdt, Int32 insuser, JobApplicationDTO jobApplication, TypeCodeDTO typeCode)
        {
			this.JobApplicationStateID = jobApplicationStateID;
			this.JobApplicationID = jobApplicationID;
			this.JobApplicationStatusID = jobApplicationStatusID;
			this.insdt = insdt;
			this.insuser = insuser;
			this.JobApplication = jobApplication;
			this.TypeCode = typeCode;
        }
    }
}
