/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class JobApplicationDTO
    {
        [DataMember()]
        public Int32 JobApplicationID { get; set; }

        [DataMember()]
        public Int32 JobID { get; set; }

        [DataMember()]
        public Int32 ApplicantUserID { get; set; }

        [DataMember()]
        public DateTime ApplicationDate { get; set; }

        [DataMember()]
        public JobDTO Job { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        [DataMember()]
        public List<JobApplicationStateDTO> JobApplicationStates { get; set; }

        public JobApplicationDTO()
        {
        }

        public JobApplicationDTO(Int32 jobApplicationID, Int32 jobID, Int32 applicantUserID, DateTime applicationDate, JobDTO job, UserDTO user, List<JobApplicationStateDTO> jobApplicationStates)
        {
			this.JobApplicationID = jobApplicationID;
			this.JobID = jobID;
			this.ApplicantUserID = applicantUserID;
			this.ApplicationDate = applicationDate;
			this.Job = job;
			this.User = user;
			this.JobApplicationStates = jobApplicationStates;
        }
    }
}
