/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class PhoneDTO
    {
        [DataMember()]
        public Int32 PhoneID { get; set; }

        [DataMember()]
        public Nullable<Int32> CountryID { get; set; }

        [DataMember()]
        public String Number { get; set; }

        [DataMember()]
        public String Ext { get; set; }

        [DataMember()]
        public Nullable<Int32> PhoneTypeID { get; set; }

        [DataMember()]
        public List<BusinessPhoneDTO> BusinessPhones { get; set; }

        [DataMember()]
        public TypeCodeDTO TypeCode { get; set; }

        [DataMember()]
        public List<UserPhoneDTO> UserPhones { get; set; }

        public PhoneDTO()
        {
        }

        public PhoneDTO(Int32 phoneID, Nullable<Int32> countryID, String number, String ext, Nullable<Int32> phoneTypeID, List<BusinessPhoneDTO> businessPhones, TypeCodeDTO typeCode, List<UserPhoneDTO> userPhones)
        {
			this.PhoneID = phoneID;
			this.CountryID = countryID;
			this.Number = number;
			this.Ext = ext;
			this.PhoneTypeID = phoneTypeID;
			this.BusinessPhones = businessPhones;
			this.TypeCode = typeCode;
			this.UserPhones = userPhones;
        }
    }
}
