/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class UserEmailDTO
    {
        [DataMember()]
        public Int32 UserEmailID { get; set; }

        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public Int32 EmailID { get; set; }

        [DataMember()]
        public Boolean IsPrimary { get; set; }

        [DataMember()]
        public EmailDTO Email { get; set; }

        [DataMember()]
        public UserDTO User { get; set; }

        public UserEmailDTO()
        {
        }

        public UserEmailDTO(Int32 userEmailID, Int32 userID, Int32 emailID, Boolean isPrimary, EmailDTO email, UserDTO user)
        {
			this.UserEmailID = userEmailID;
			this.UserID = userID;
			this.EmailID = emailID;
			this.IsPrimary = isPrimary;
			this.Email = email;
			this.User = user;
        }
    }
}
