/*
Project: Jobs In ABA
Authoer: Ghanshyam Bhalala
Date Created: 2015-12-04

*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/01/01 - 02:55:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace JobsInABA.DTOs
{
    [DataContract()]
    public partial class UserDTO
    {
        [DataMember()]
        public Int32 UserID { get; set; }

        [DataMember()]
        public String UserName { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String MiddleName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public Nullable<DateTime> DOB { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        [DataMember()]
        public Nullable<Int32> insuser { get; set; }

        [DataMember()]
        public Nullable<DateTime> insdt { get; set; }

        [DataMember()]
        public Nullable<Int32> upduser { get; set; }

        [DataMember()]
        public Nullable<DateTime> upddt { get; set; }

        [DataMember()]
        public List<BusinessDTO> Businesses { get; set; }

        [DataMember()]
        public List<BusinessDTO> Businesses1 { get; set; }

        [DataMember()]
        public List<BusinessUserMapDTO> BusinessUserMaps { get; set; }

        [DataMember()]
        public List<JobApplicationDTO> JobApplications { get; set; }

        [DataMember()]
        public List<UserAccountDTO> UserAccounts { get; set; }

        [DataMember()]
        public List<UserAddressDTO> UserAddresses { get; set; }

        [DataMember()]
        public List<UserEmailDTO> UserEmails { get; set; }

        [DataMember()]
        public List<UserPhoneDTO> UserPhones { get; set; }

        [DataMember()]
        public List<UserRoleDTO> UserRoles { get; set; }

        [DataMember()]
        public List<UserDTO> Users1 { get; set; }

        [DataMember()]
        public UserDTO User1 { get; set; }

        [DataMember()]
        public List<UserDTO> Users11 { get; set; }

        [DataMember()]
        public UserDTO User2 { get; set; }

        public UserDTO()
        {
        }

        public UserDTO(Int32 userID, String userName, String firstName, String middleName, String lastName, Nullable<DateTime> dOB, Boolean isActive, Boolean isDeleted, Nullable<Int32> insuser, Nullable<DateTime> insdt, Nullable<Int32> upduser, Nullable<DateTime> upddt, List<BusinessDTO> businesses, List<BusinessDTO> businesses1, List<BusinessUserMapDTO> businessUserMaps, List<JobApplicationDTO> jobApplications, List<UserAccountDTO> userAccounts, List<UserAddressDTO> userAddresses, List<UserEmailDTO> userEmails, List<UserPhoneDTO> userPhones, List<UserRoleDTO> userRoles, List<UserDTO> users1, UserDTO user1, List<UserDTO> users11, UserDTO user2)
        {
			this.UserID = userID;
			this.UserName = userName;
			this.FirstName = firstName;
			this.MiddleName = middleName;
			this.LastName = lastName;
			this.DOB = dOB;
			this.IsActive = isActive;
			this.IsDeleted = isDeleted;
			this.insuser = insuser;
			this.insdt = insdt;
			this.upduser = upduser;
			this.upddt = upddt;
			this.Businesses = businesses;
			this.Businesses1 = businesses1;
			this.BusinessUserMaps = businessUserMaps;
			this.JobApplications = jobApplications;
			this.UserAccounts = userAccounts;
			this.UserAddresses = userAddresses;
			this.UserEmails = userEmails;
			this.UserPhones = userPhones;
			this.UserRoles = userRoles;
			this.Users1 = users1;
			this.User1 = user1;
			this.Users11 = users11;
			this.User2 = user2;
        }
    }
}
